export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const TEXT_PREDICTION_SUCCESS = 'TEXT_PREDICTION_SUCCESS';