export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const TEXT_PREDICTION_START = 'TEXT_PREDICTION_START';
export const TEXT_PREDICTION_SUCCESS = 'TEXT_PREDICTION_SUCCESS';

export const FETCH_SUMMARY_START = 'FETCH_SUMMARY_START';
export const FETCH_SUMMARY_SUCCESS = 'FETCH_SUMMARY_SUCCESS';

export const FILE_PREDICTION_START = 'FILE_PREDICTION_START';
export const FILE_PREDICTION_SUCCESS = 'FILE_PREDICTION_SUCCESS';

export const TRAIN_ALGO_START = "TRAIN_ALGO_START";
export const TRAIN_ALGO_SUCCESS = "TRAIN_ALGO_SUCCESS";

export const FETCH_HISTORY_START = 'FETCH_HISTORY_START';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';